const MAP_TYPES = {STANDARD: 'standard', SATELLITE: 'hybrid'};

const DELIVERY_STATUS = {
  PRODUCTION: 'PRODUCTION',
  TRANSIT: 'TRANSIT',
  ONSITE: 'ONSITE',
  DELIVERED: 'DELIVERED',
};

export {MAP_TYPES, DELIVERY_STATUS};
